services:
  postgres:
    ports: []

  fastapi:
    image: ghcr.io/ye11ow-banana/main-be:latest
    build: {}
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  develop:
    profiles: ["dev"]

  mailpit:
    profiles: ["dev"]

  nginx:
    ports:
      - "80:80"
