services:
  postgres:
    ports: []

  fastapi:
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    develop: null

  develop:
    profiles: ["dev"]

  mailpit:
    profiles: ["dev"]

  nginx:
    ports:
      - "80:80"
