version: '3'

tasks:
  default:
    desc: Run format and tests
    cmds:
      - task: format
      - task: test

  format:
    desc: Format code
    cmds:
      - ruff format

  test:
    desc: Run tests
    cmds:
      - pytest

  m:new:
    desc: Create a new Alembic migration with autogeneration
    cmds:
      - docker compose run --rm develop alembic revision --autogenerate -m "{{.MSG}}"

  m:upgrade:
    desc: Apply latest Alembic migrations
    cmds:
      - docker compose run --rm develop alembic upgrade head

  m:downgrade:
    desc: Revert the last Alembic migration
    cmds:
      - docker compose run --rm develop alembic downgrade "-1"

  d:build:
    desc: Build Docker image for FastAPI services
    cmds:
      - docker compose build fastapi

  d:up:
    desc: Run full stack with Docker Compose
    cmds:
      - docker compose up -d --remove-orphans

  d:watch:
    desc: Sync code changes into container with Compose Watch (no rebuilds for code)
    cmds:
      - docker compose watch