"""Remove user_id field as PK

Revision ID: 45d651d25b98
Revises: 70bf4abe4060
Create Date: 2025-12-19 00:11:20.505377

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "45d651d25b98"
down_revision: Union[str, Sequence[str], None] = "70bf4abe4060"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
