"""Add auto updated_at

Revision ID: 7a9d06f62d10
Revises: d15b840c21d5
Create Date: 2026-01-22 10:14:07.190178

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a9d06f62d10"
down_revision: Union[str, Sequence[str], None] = "d15b840c21d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "days",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("timezone('utc', now())"),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "days",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=None,
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
