"""Add totals to days table

Revision ID: 26e004ae4c79
Revises: 71c330370dd0
Create Date: 2026-01-27 09:39:59.193509

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26e004ae4c79"
down_revision: Union[str, Sequence[str], None] = "71c330370dd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "days",
        sa.Column("total_proteins", sa.Numeric(), nullable=False, server_default="0"),
    )
    op.add_column(
        "days",
        sa.Column("total_fats", sa.Numeric(), nullable=False, server_default="0"),
    )
    op.add_column(
        "days",
        sa.Column("total_carbs", sa.Numeric(), nullable=False, server_default="0"),
    )
    op.add_column(
        "days",
        sa.Column("total_calories", sa.Numeric(), nullable=False, server_default="0"),
    )
    op.alter_column(
        "days",
        "additional_calories",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "days",
        "additional_calories",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("'0'::numeric"),
        existing_nullable=False,
    )
    op.drop_column("days", "total_calories")
    op.drop_column("days", "total_carbs")
    op.drop_column("days", "total_fats")
    op.drop_column("days", "total_proteins")
    # ### end Alembic commands ###
