"""Add 3 new tables for the new calorie app

Revision ID: 382d5b26955c
Revises: 4d598c3fe30a
Create Date: 2025-12-27 16:48:14.516002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "382d5b26955c"
down_revision: Union[str, Sequence[str], None] = "4d598c3fe30a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("proteins", sa.Numeric(), nullable=False),
        sa.Column("fats", sa.Numeric(), nullable=False),
        sa.Column("carbs", sa.Numeric(), nullable=False),
        sa.Column("calories", sa.Numeric(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_table(
        "days",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("body_weight", sa.Numeric(), nullable=True),
        sa.Column("body_fat", sa.Numeric(), nullable=True),
        sa.Column("trend", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_days_id"), "days", ["id"], unique=False)
    op.create_table(
        "day_products",
        sa.Column("day_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(["day_id"], ["days.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("day_id", "product_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("day_products")
    op.drop_index(op.f("ix_days_id"), table_name="days")
    op.drop_table("days")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
