"""Add verification_codes table

Revision ID: 70bf4abe4060
Revises: 40472044e26b
Create Date: 2025-12-19 00:08:05.071712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70bf4abe4060"
down_revision: Union[str, Sequence[str], None] = "40472044e26b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "user_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_verification_codes_id"), "verification_codes", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_codes_id"), table_name="verification_codes")
    op.drop_table("verification_codes")
    # ### end Alembic commands ###
