"""Add new field additional_calories to days table

Revision ID: 71c330370dd0
Revises: 582a8853356c
Create Date: 2026-01-26 13:45:52.016876

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71c330370dd0"
down_revision: Union[str, Sequence[str], None] = "582a8853356c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "days",
        sa.Column(
            "additional_calories", sa.Numeric(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("days", "additional_calories")
    # ### end Alembic commands ###
