"""add teams table

Revision ID: af99dc1e7da9
Revises: 3112835c5adc
Create Date: 2026-04-29 11:59:49.736343

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af99dc1e7da9"
down_revision: Union[str, Sequence[str], None] = "d8d3b50de011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("requester_id", sa.UUID(), nullable=False),
        sa.Column("addressee_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["addressee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=False)
    op.create_index(
        "uq_teams_user_pair",
        "teams",
        [
            sa.text("LEAST(requester_id, addressee_id)"),
            sa.text("GREATEST(requester_id, addressee_id)"),
        ],
        unique=True,
    )
    op.alter_column(
        "days",
        "total_proteins",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "days",
        "total_fats",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "days",
        "total_carbs",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "days",
        "total_calories",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "days",
        "total_calories",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("'0'::numeric"),
        existing_nullable=False,
    )
    op.alter_column(
        "days",
        "total_carbs",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("'0'::numeric"),
        existing_nullable=False,
    )
    op.alter_column(
        "days",
        "total_fats",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("'0'::numeric"),
        existing_nullable=False,
    )
    op.alter_column(
        "days",
        "total_proteins",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("'0'::numeric"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_index("uq_teams_user_pair", table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
