"""Add 3 new tables for the new calorie app

Revision ID: c11fbb840c57
Revises: 4d598c3fe30a
Create Date: 2025-12-26 23:04:49.783899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c11fbb840c57"
down_revision: Union[str, Sequence[str], None] = "4d598c3fe30a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
