"""Change type of weight field in day_products table

Revision ID: d15b840c21d5
Revises: d29c683628af
Create Date: 2026-01-09 22:53:11.642558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d15b840c21d5"
down_revision: Union[str, Sequence[str], None] = "d29c683628af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "day_products",
        "weight",
        existing_type=sa.NUMERIC(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_products_name_trgm"),
        table_name="products",
        postgresql_ops={"lower(name::text)": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_products_name_trgm"),
        "products",
        [sa.literal_column("lower(name::text)")],
        unique=False,
        postgresql_ops={"lower(name::text)": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.alter_column(
        "day_products",
        "weight",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
